### ISSUE TITLE
Ændring i Economic 

### ISSUE THREAD

**Issue by dyrehauge** [kristiannissen/PHPEconomics#19]
Hej Kristian,
Hos Morning train har vi arbejdet lidt med din løsning til woo-economics. Du står selvfølgelig stadigvæk som author. Ville du være interesseret i at jeg sender dig koden så du kan kigge den igennem, eller er du ok med at vi uploader vores løsning på vores github? 

mvh. Morning train.

**Comment by kristiannissen** [comment]
Hej

ja, jeg har længe haft en ambition om at få projektet opdateret og forbedret, send mig hvad I har :)
